site_name: OpenAPI
repo_url: https://github.com/Dyalog/OpenAPI
repo_name: Dyalog/OpenAPI
copyright: Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener"><strong>Material for MkDocs</strong></a><br/>Copyright &copy; 1982-$CURRENT_YEAR <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog Limited</a></strong> (<a href="#" class="copy" onclick="navigator.clipboard.writeText(innerText);return false" title="Click to copy!">$BUILD_DATE $GIT_INFO</a>).<br/>Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"><strong>Creative Commons Attribution 4.0 International</strong></a> licence.

theme:
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - content.tabs.link
  name: material
  font:
      text: Be Vietnam Pro
  custom_dir: docs/documentation-assets/overrides
extra_css:
  - documentation-assets/css/main.css
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

nav:
  - Home: index.md
  - Installation: installation.md
  - Using the Generator:
    - Overview: usage/index.md
    - CLI Reference: usage/cli.md
    - Troubleshooting: usage/troubleshooting.md
  - Generated Client:
    - Overview: generated-client/index.md
    - Client Class: generated-client/client.md
    - Utilities: generated-client/utils.md
    - Operation Functions: generated-client/operations.md
    - Using the Client: generated-client/using-the-client.md
    - Error Handling: generated-client/error-handling.md
  - Examples:
    - Overview: examples/index.md
    - Petstore: examples/petstore.md
    - Authentication: examples/authentication.md
    - Debugging: examples/debugging.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - toc:
      title: On this page